### ISSUE TITLE
Keybinds should be configurable

### ISSUE THREAD

**Issue by weepingminotaur** [reonZ/pf2e-effect-description#2]
Great module! Would be even better if the keybinds for each action (open sheet, send to chat) were configurable, rather than hardcoded, given that Foundry allows configuration of keybinds in the Configure Controls menu.

**Comment by reonZ** [comment]
I have never worked with the foundry's binding system so i would need to look into it, but i am already behind in quite a few things for my other modules, so i dunno if or when i will eventually tackle on this.

There are not that many options possible in the end to justify customizable binds.

**Comment by reonZ** [comment]
Sorry, but i don't plan on implementing custom bindings for the module
