### ISSUE TITLE
shift-right-click doesn't work

### ISSUE THREAD

**Issue by dharkus5000** [reonZ/pf2e-effect-description#8]
when i shift right click it just brings up the standard right click box that'd come up if i wasn't on foundry, where right click is overridden, shift seems to override that, and brings it up, and this means that shift right click therefore does nothing at all
i'm on firefox btw

**Comment by reonZ** [comment]
The `shift right click` of the module just remove the effect entirely instead of having to remove each counter one by one until the effect is gone.

I don't know of any " standard right click box" so if you could give me more details on that.


https://github.com/reonZ/pf2e-effect-description/assets/651462/b639b902-6096-4848-a9ad-c9c6047ed345

**Comment by dharkus5000** [comment]
![image](https://github.com/reonZ/pf2e-effect-description/assets/88220878/cd536c13-0b5d-4c37-83ab-cd11e3bf9894)
screenshot of the email i got for this msg, and me right clicking, i get
the same "right click box" when i shift right click the effect in foundry,
and when i right click this email in gmail, in the same browser

**Comment by reonZ** [comment]
Sorry but i don't understand what you are saying, what "right click box" are you talking about ? also you didn't link any screenshot, you typed `[image: image.png]`

![image](https://github.com/reonZ/pf2e-effect-description/assets/651462/dcbdde5d-abeb-4c36-94ab-30f2e919ed73)

**Comment by dharkus5000** [comment]
i didn't type that, i replied to the email, it seems it ate the screenshot
- guess i'll login to github...

**Comment by dharkus5000** [comment]
![image](https://github.com/reonZ/pf2e-effect-description/assets/88220878/e24a3262-6c57-41eb-88e7-f6a73f8f617a)

**Comment by reonZ** [comment]
What am i supposed to do with that ? it is the message i typed, it doesn't answer my question.

What is that "right click box" you are referring to ? the module works fine.

**Comment by dharkus5000** [comment]
you don't see that big black box that has save page as etc on it?  that's what i see when i do shift right click on an effect, and the effect is the unaffected

**Comment by reonZ** [comment]
Ok i finally understand what you meant and it is definitely a firefox issue, just so you know, foundry official support is with chromium so using firefox for foundry isn't advised.

I checked and firefox doesn't allow the use of `shift + right click`, i will add a new setting to replace it with `ctrl`

**Comment by reonZ** [comment]
You can now also use `[Ctrl + Right Click]` to remove the effect, this won't be displayed in the effect tooltip though.

**Comment by dharkus5000** [comment]
ah cool, thx
